FROM postgres:16

# Install CA certificates and pgvector
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        postgresql-16-pgvector \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
